#!/usr/bin/python

import MySQLdb

# Open database connection
db = MySQLdb.connect("192.168.0.103","root","lsn@1994","cloud_robotics" )

# prepare a cursor object using cursor() method
cursor = db.cursor()

# Prepare SQL query to INSERT a record into the database.
sql = """SELECT * FROM LOGIN"""
try:
   # Execute the SQL command
   cursor.execute(sql)
   # Commit your changes in the database
   db.commit()
except:
   # Rollback in case there is any error
   db.rollback()

# disconnect from server
db.close()
